const char assets_style_css[] =
"body {background-color: #EAEAEA; color: #333333; font-family: \"Times New Roman\", serif; margin: 0; padding: 0;}\n"
"h1, h2, h3 {color: #1E4D8C;}\n"
"a {color: #0066CC;}\n"
"a:visited {color: #0066CC;}\n"
".container {width: 100%; margin: 0; padding: 0;}\n"
".header {background-color: #3A7CA5; padding: 10px; height: 80px; text-align: center; color: #FFFFFF;}\n"
".header h1, .header h2 {color: #FFFFFF; margin: 5px 0;}\n"
".header img { float: left; height: 100%; margin-right:10px; }\n"
".content {padding: 10px; background-color: #FFFFFF; min-height: 300px;}\n"
".footer {background-color: #3A7CA5; padding: 10px; text-align: center; color: #FFFFFF;}\n"
"p {margin-bottom: 10px;}\n"
".button {background-color: #4CAF50; padding: 7px 15px; text-decoration: none; border: 1px solid #2E8B57; color: #FFFFFF; margin: 5px; display: inline-block;}\n"
".info-box {background-color: #F5F5F5; padding: 10px; margin: 10px 0;}\n"
".warning {background-color: #FFDDDD; padding: 10px; margin: 10px 0; color: #990000;}\n"
".file-link {padding: 8px; margin: 5px 0; display: block; font-size: 16px; word-wrap: break-word; overflow-wrap: break-word;}\n"
".file-link-even {background-color: #E3F2FD;}\n"
".file-link-odd {background-color: #BBDEFB;}\n"
".header-bar {background-color: #2C5F7C; color: #FFFFFF; padding: 5px;}\n"
".usb-info {background-color: #E3F2FD; border-top: 1px solid #BBDEFB; padding: 5px; text-align: center; margin-top: 20px;}\n"
".build-info {font-size: 9px; text-align: left; color: #CCCCCC; padding: 5px 0 0 5px; margin-top: 2px;}\n"
".pagination {display: flex; justify-content: center; margin: 15px 0; background-color: #F5F5F5; padding: 8px; border-radius: 3px;}\n"
".pagination a, .pagination span {margin: 0 3px; padding: 4px 8px; text-decoration: none; color: #0066CC; border: 1px solid #BBDEFB; background-color: #E3F2FD;}\n"
".pagination .current {background-color: #3A7CA5; color: #FFFFFF; border-color: #2C5F7C;}\n"
".pagination a:hover {background-color: #BBDEFB;}\n"
".page-info {text-align: center; margin: 5px 0; font-size: 14px; color: #666;}\n"
"#log {width:80%; height:600px; border:1px solid #ccc; padding:8px; overflow-y:scroll; overflow-x:auto; font-family:monospace; white-space:pre; background-color:#f9f9f9;}\n"
".current {font-weight:bold; border:2px solid #4CAF50;}\n"
".center {text-align: center;}\n"
".margin {margin: 30px 0;}\n"
".message {background-color: #E3F2FD; padding: 10px; margin: 10px 0; border-left: 4px solid #2196F3;}\n"
".unavailable {color: #666; font-style: italic;}\n"
;
const unsigned int assets_style_css_len = sizeof(assets_style_css) - 1;
