"<div class=\"navigation\">\n"
"                <a href=\"/\" class=\"button\">Back to Home</a>\n"
"            </div>\n"
"\n"
"            {{#error_message}}\n"
"            <div class=\"warning\">\n"
"                <strong>Error:</strong> {{error_message}}\n"
"            </div>\n"
"            {{/error_message}}\n"
"\n"
"            {{#success_message}}\n"
"            <div class=\"success\">\n"
"                <strong>Success:</strong> {{success_message}}\n"
"            </div>\n"
"            {{/success_message}}\n"
"\n"
"            <form method=\"POST\" action=\"/config\">\n"
"                <div class=\"form-section\">\n"
"                    <h3>Display Configuration</h3>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"displayhat\">Display HAT Type:</label>\n"
"                        <div class=\"current-value\">Current: {{current_displayhat}}</div>\n"
"                        <select name=\"displayhat\" id=\"displayhat\">\n"
"                            <option value=\"none\" {{#displayhat_none}}selected{{/displayhat_none}}>None</option>\n"
"                            <option value=\"pirateaudiolineout\" {{#displayhat_pirateaudio}}selected{{/displayhat_pirateaudio}}>Pirate Audio Line Out</option>\n"
"                            <option value=\"waveshare\" {{#displayhat_waveshare}}selected{{/displayhat_waveshare}}>Waveshare OLED</option>\n"
"                            <option value=\"sh1106\" {{#displayhat_sh1106}}selected{{/displayhat_sh1106}}>Generic SH1106 OLED</option>\n"
"                            <option value=\"st7789\" {{#displayhat_st7789}}selected{{/displayhat_st7789}}>Generic ST7789 OLED</option>\n"
"                        </select>\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"screen_timeout\">Screen Timeout (seconds):</label>\n"
"                        <div class=\"current-value\">Current: {{current_screen_timeout}} seconds</div>\n"
"                        <input type=\"text\" name=\"screen_timeout\" id=\"screen_timeout\" value=\"{{screen_timeout}}\" size=\"6\">\n"
"                        <div class=\"current-value\">Set to 0 to disable timeout</div>\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"st7789_brightness\">PirateAudioLineOut Display Brightness:</label>\n"
"                        <div class=\"current-value\">Current: {{current_st7789_brightness}}</div>\n"
"                        <input type=\"number\" name=\"st7789_brightness\" id=\"st7789_brightness\" value=\"{{st7789_brightness}}\" min=\"0\" max=\"4095\">\n"
"                        <div class=\"current-value\">Range: 0-1024 (0 is off, 1024 is default)</div>\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"st7789_sleep_brightness\">PirateAudioLineOut Sleep Brightness:</label>\n"
"                        <div class=\"current-value\">Current: {{current_st7789_sleep_brightness}}</div>\n"
"                        <input type=\"number\" name=\"st7789_sleep_brightness\" id=\"st7789_sleep_brightness\" value=\"{{st7789_sleep_brightness}}\" min=\"0\" max=\"4095\">\n"
"                        <div class=\"current-value\">Range: 0-1024 (0 is off, 32 is default)</div>\n"
"                    </div>\n"
"                </div>\n"
"\n"
"                <div class=\"form-section\">\n"
"                    <h3>Audio Configuration</h3>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"sounddev\">Sound Device:</label>\n"
"                        <div class=\"current-value\">Current: {{current_sounddev}}</div>\n"
"                        <select name=\"sounddev\" id=\"sounddev\">\n"
"                            <option value=\"sndpwm\" {{#sounddev_sndpwm}}selected{{/sounddev_sndpwm}}>PWM Audio (3.5mm jack)</option>\n"
"                            <option value=\"sndi2s\" {{#sounddev_sndi2s}}selected{{/sounddev_sndi2s}}>I2S Audio (HATs)</option>\n"
"                            <option value=\"sndhdmi\" {{#sounddev_sndhdmi}}selected{{/sounddev_sndhdmi}}>HDMI Audio</option>\n"
"                        </select>\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"default_volume\">CD Audio Out Volume:</label>\n"
"                        <div class=\"current-value\">Current: {{current_default_volume}}</div>\n"
"                        <input type=\"number\" id=\"default_volume\" name=\"default_volume\" min=\"0\" max=\"255\" value=\"{{current_default_volume}}\">\n"
"                        <div class=\"current-value\">Set to 0 for silent, 255 maximum (255 is default)</div>\n"
"                    </div>\n"
"                </div>\n"
"\n"
"                <div class=\"form-section\">\n"
"                    <h3>USB Configuration</h3>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"usbspeed\">USB Speed:</label>\n"
"                        <div class=\"current-value\">Current: {{current_usbspeed}}</div>\n"
"                        <select name=\"usbspeed\" id=\"usbspeed\">\n"
"                            <option value=\"high\" {{#usbspeed_high}}selected{{/usbspeed_high}}>High Speed (USB 2.0)</option>\n"
"                            <option value=\"full\" {{#usbspeed_full}}selected{{/usbspeed_full}}>Full Speed (USB 1.1)</option>\n"
"                        </select>\n"
"                        <div class=\"current-value\">Use Full Speed for better compatibility with retro computers</div>\n"
"                    </div>\n"
"                </div>\n"
"\n"
"                <div class=\"form-section\">\n"
"                    <h3>Logging Configuration</h3>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"logfile\">Log File Path:</label>\n"
"                        <div class=\"current-value\">Current: {{current_logfile}}</div>\n"
"                        <input type=\"text\" name=\"logfile\" id=\"logfile\" value=\"{{logfile}}\" size=\"30\">\n"
"                        <div class=\"current-value\">Leave empty to disable file logging. Will be automatically prefixed with 0:/</div>\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"loglevel\">Log Level:</label>\n"
"                        <div class=\"current-value\">Current: {{current_loglevel}}</div>\n"
"                        <select name=\"loglevel\" id=\"loglevel\">\n"
"                            <option value=\"0\" {{#loglevel_0}}selected{{/loglevel_0}}>0 - No logging</option>\n"
"                            <option value=\"1\" {{#loglevel_1}}selected{{/loglevel_1}}>1 - Panic only</option>\n"
"                            <option value=\"2\" {{#loglevel_2}}selected{{/loglevel_2}}>2 - Errors and panics</option>\n"
"                            <option value=\"3\" {{#loglevel_3}}selected{{/loglevel_3}}>3 - Warnings, errors, panics</option>\n"
"                            <option value=\"4\" {{#loglevel_4}}selected{{/loglevel_4}}>4 - Notes, warnings, errors, panics</option>\n"
"                            <option value=\"5\" {{#loglevel_5}}selected{{/loglevel_5}}>5 - Debug (all messages)</option>\n"
"                        </select>\n"
"                    </div>\n"
"                </div>\n"
"\n"
"                <div class=\"info-box\">\n"
"                    <strong>Note:</strong> Changes will take effect after reboot. Some settings may require a complete power cycle.\n"
"                </div>\n"
"\n"
"                <div style=\"text-align: center; margin: 30px 0;\">\n"
"                    <button type=\"submit\" name=\"action\" value=\"save\" class=\"button\">Save Configuration</button>\n"
"                    <button type=\"submit\" name=\"action\" value=\"save_reboot\" class=\"button\">Save & Reboot</button>\n"
"                    <button type=\"submit\" name=\"action\" value=\"save_shutdown\" class=\"button\">Save & Shutdown</button>\n"
"                    <a href=\"/\" class=\"button button-danger\">Cancel</a>\n"
"                </div>\n"
"            </form>\n"
"            \n"
"            <!-- Sound test form moved outside main form -->\n"
"            {{#sound_test_available}}\n"
"            <div class=\"form-section\">\n"
"                <h3>Audio Test</h3>\n"
"                <form method=\"POST\" action=\"/config\">\n"
"                    <div class=\"form-group\">\n"
"                        <label>Audio Test:</label>\n"
"                        <div class=\"current-value\">Test audio output functionality (computer generated sound runs for about 6 seconds)</div>\n"
"                        <input type=\"hidden\" name=\"action\" value=\"soundtest\">\n"
"                        <button type=\"submit\" class=\"button\">Execute Sound Test</button>\n"
"                    </div>\n"
"                </form>\n"
"                \n"
"                {{#message}}\n"
"                <div style=\"background-color: #E3F2FD; padding: 10px; margin: 10px 0; border-left: 4px solid #2196F3;\">{{message}}</div>\n"
"                {{/message}}\n"
"            </div>\n"
"            {{/sound_test_available}}\n"
"            \n"
"            {{^sound_test_available}}\n"
"            <div class=\"form-section\">\n"
"                <h3>Audio Test</h3>\n"
"                <div class=\"form-group\">\n"
"                    <label>Audio Test:</label>\n"
"                    <div class=\"current-value\" style=\"color: #666; font-style: italic;\">Sound test not available (not in CDROM mode or sound not enabled)</div>\n"
"                </div>\n"
"            </div>\n"
"            {{/sound_test_available}}\n"
"\n"
""