"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <title>USBODE Configuration</title>\n"
"    <style>\n"
"        body {background-color: #EAEAEA; color: #333333; font-family: \"Times New Roman\", serif; margin: 0; padding: 0;}\n"
"        h1, h2, h3 {color: #1E4D8C;}\n"
"        a {color: #0066CC;}\n"
"        a:visited {color: #0066CC;}\n"
"        .container {width: 100%; margin: 0; padding: 0;}\n"
"        .header {background-color: #3A7CA5; padding: 10px; height: 80px; text-align: center; color: #FFFFFF;}\n"
"        .header h1, .header h2 {color: #FFFFFF; margin: 5px 0;}\n"
"        .content {padding: 20px; background-color: #FFFFFF; min-height: 400px;}\n"
"        .footer {background-color: #3A7CA5; padding: 10px; text-align: center; color: #FFFFFF;}\n"
"        .button {background-color: #4CAF50; padding: 10px 20px; text-decoration: none; color: #FFFFFF; margin: 10px 5px; display: inline-block; border: none; cursor: pointer; font-size: 16px;}\n"
"        .button:hover {background-color: #45a049;}\n"
"        .button-danger {background-color: #f44336;}\n"
"        .button-danger:hover {background-color: #da190b;}\n"
"        .info-box {background-color: #F5F5F5; padding: 15px; margin: 15px 0; border-left: 4px solid #3A7CA5;}\n"
"        .warning {background-color: #FFDDDD; padding: 15px; margin: 15px 0; color: #990000; border-left: 4px solid #ff0000;}\n"
"        .success {background-color: #DDFFDD; padding: 15px; margin: 15px 0; color: #006600; border-left: 4px solid #00aa00;}\n"
"        .form-group {margin: 15px 0;}\n"
"        .form-group label {display: block; margin-bottom: 5px; font-weight: bold;}\n"
"        .form-group select, .form-group input[type=\"text\"], .form-group input[type=\"number\"] {\n"
"            width: 300px; padding: 8px; border: 1px solid #ccc; border-radius: 4px; font-size: 14px;\n"
"        }\n"
"        .form-section {background-color: #f9f9f9; padding: 20px; margin: 20px 0; border-radius: 5px; border: 1px solid #ddd;}\n"
"        .form-section h3 {margin-top: 0; color: #1E4D8C; border-bottom: 2px solid #3A7CA5; padding-bottom: 10px;}\n"
"        .current-value {color: #666; font-style: italic; font-size: 12px;}\n"
"        .navigation {margin: 20px 0;}\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <div class=\"header\">\n"
"            <img src=\"/logo.jpg\" alt=\"Logo\" align=\"left\" height=\"100%\" style=\"margin-right:10px;\">\n"
"            <h1>USBODE</h1>\n"
"            <h2>Configuration</h2>\n"
"        </div>\n"
"        \n"
"        <div class=\"content\">\n"
"            <div class=\"navigation\">\n"
"                <a href=\"/\" class=\"button\">← Back to Home</a>\n"
"            </div>\n"
"\n"
"            {{#error_message}}\n"
"            <div class=\"warning\">\n"
"                <strong>Error:</strong> {{error_message}}\n"
"            </div>\n"
"            {{/error_message}}\n"
"\n"
"            {{#success_message}}\n"
"            <div class=\"success\">\n"
"                <strong>Success:</strong> {{success_message}}\n"
"            </div>\n"
"            {{/success_message}}\n"
"\n"
"            <form method=\"POST\" action=\"/config\">\n"
"                <div class=\"form-section\">\n"
"                    <h3>Display Configuration</h3>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"displayhat\">Display HAT Type:</label>\n"
"                        <div class=\"current-value\">Current: {{current_displayhat}}</div>\n"
"                        <select name=\"displayhat\" id=\"displayhat\">\n"
"                            <option value=\"none\" {{#displayhat_none}}selected{{/displayhat_none}}>None</option>\n"
"                            <option value=\"pirateaudiolineout\" {{#displayhat_pirateaudio}}selected{{/displayhat_pirateaudio}}>Pirate Audio Line Out</option>\n"
"                            <option value=\"waveshare\" {{#displayhat_waveshare}}selected{{/displayhat_waveshare}}>Waveshare OLED</option>\n"
"                        </select>\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"screen_timeout\">Screen Timeout (seconds):</label>\n"
"                        <div class=\"current-value\">Current: {{current_screen_timeout}} seconds</div>\n"
"                        <input type=\"number\" name=\"screen_timeout\" id=\"screen_timeout\" value=\"{{screen_timeout}}\" min=\"0\" max=\"3600\">\n"
"                        <div class=\"current-value\">Set to 0 to disable timeout</div>\n"
"                    </div>\n"
"                </div>\n"
"\n"
"                <div class=\"form-section\">\n"
"                    <h3>Audio Configuration</h3>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"sounddev\">Sound Device:</label>\n"
"                        <div class=\"current-value\">Current: {{current_sounddev}}</div>\n"
"                        <select name=\"sounddev\" id=\"sounddev\">\n"
"                            <option value=\"sndpwm\" {{#sounddev_sndpwm}}selected{{/sounddev_sndpwm}}>PWM Audio (3.5mm jack)</option>\n"
"                            <option value=\"sndi2s\" {{#sounddev_sndi2s}}selected{{/sounddev_sndi2s}}>I2S Audio (HATs)</option>\n"
"                            <option value=\"sndhdmi\" {{#sounddev_sndhdmi}}selected{{/sounddev_sndhdmi}}>HDMI Audio</option>\n"
"                            <option value=\"sndusb\" {{#sounddev_sndusb}}selected{{/sounddev_sndusb}}>USB Audio (Pi 4 only)</option>\n"
"                        </select>\n"
"                    </div>\n"
"                </div>\n"
"\n"
"                <div class=\"form-section\">\n"
"                    <h3>USB Configuration</h3>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"usbspeed\">USB Speed:</label>\n"
"                        <div class=\"current-value\">Current: {{current_usbspeed}}</div>\n"
"                        <select name=\"usbspeed\" id=\"usbspeed\">\n"
"                            <option value=\"high\" {{#usbspeed_high}}selected{{/usbspeed_high}}>High Speed (USB 2.0)</option>\n"
"                            <option value=\"full\" {{#usbspeed_full}}selected{{/usbspeed_full}}>Full Speed (USB 1.1)</option>\n"
"                        </select>\n"
"                        <div class=\"current-value\">Use Full Speed for better compatibility with retro computers</div>\n"
"                    </div>\n"
"                </div>\n"
"\n"
"                <div class=\"form-section\">\n"
"                    <h3>Logging Configuration</h3>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"logfile\">Log File Path:</label>\n"
"                        <div class=\"current-value\">Current: {{current_logfile}}</div>\n"
"                        <input type=\"text\" name=\"logfile\" id=\"logfile\" value=\"{{logfile}}\" placeholder=\"usbode-logs.txt\">\n"
"                        <div class=\"current-value\">Leave empty to disable file logging. Will be automatically prefixed with SD:/</div>\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"loglevel\">Log Level:</label>\n"
"                        <div class=\"current-value\">Current: {{current_loglevel}}</div>\n"
"                        <select name=\"loglevel\" id=\"loglevel\">\n"
"                            <option value=\"0\" {{#loglevel_0}}selected{{/loglevel_0}}>0 - No logging</option>\n"
"                            <option value=\"1\" {{#loglevel_1}}selected{{/loglevel_1}}>1 - Panic only</option>\n"
"                            <option value=\"2\" {{#loglevel_2}}selected{{/loglevel_2}}>2 - Errors and panics</option>\n"
"                            <option value=\"3\" {{#loglevel_3}}selected{{/loglevel_3}}>3 - Warnings, errors, panics</option>\n"
"                            <option value=\"4\" {{#loglevel_4}}selected{{/loglevel_4}}>4 - Notes, warnings, errors, panics</option>\n"
"                            <option value=\"5\" {{#loglevel_5}}selected{{/loglevel_5}}>5 - Debug (all messages)</option>\n"
"                        </select>\n"
"                    </div>\n"
"                </div>\n"
"\n"
"                <div class=\"info-box\">\n"
"                    <strong>Note:</strong> Changes will take effect after reboot. Some settings may require a complete power cycle.\n"
"                </div>\n"
"\n"
"                <div style=\"text-align: center; margin: 30px 0;\">\n"
"                    <button type=\"submit\" class=\"button\">Save Configuration</button>\n"
"                    <a href=\"/\" class=\"button button-danger\">Cancel</a>\n"
"                </div>\n"
"            </form>\n"
"        </div>\n"
"        \n"
"        <div class=\"footer\">\n"
"            <p>&copy; 2024 USBODE Project</p>\n"
"        </div>\n"
"    </div>\n"
"</body>\n"
"</html>\n"
""