"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <title>USBODE - USB Optical Drive Emulator</title>\n"
"    <style>\n"
"        body {background-color: #EAEAEA; color: #333333; font-family: \"Times New Roman\", serif; margin: 0; padding: 0;}\n"
"        h1, h2, h3 {color: #1E4D8C;}\n"
"        a {color: #0066CC;}\n"
"        a:visited {color: #0066CC;}\n"
"        .container {width: 100%; margin: 0; padding: 0;}\n"
"        .header {background-color: #3A7CA5; padding: 10px; height: 80px; text-align: center; color: #FFFFFF;}\n"
"        .header h1, .header h2 {color: #FFFFFF; margin: 5px 0;}\n"
"        .content {padding: 10px; background-color: #FFFFFF; min-height: 300px;}\n"
"        .footer {background-color: #3A7CA5; padding: 10px; text-align: center; color: #FFFFFF;}\n"
"        .button {background-color: #4CAF50; padding: 7px 15px; text-decoration: none; color: #FFFFFF; margin: 5px; display: inline-block;}\n"
"        .info-box {background-color: #F5F5F5; padding: 10px; margin: 10px 0;}\n"
"        .warning {background-color: #FFDDDD; padding: 10px; margin: 10px 0; color: #990000;}\n"
"        .file-link {padding: 8px; margin: 5px 0; display: block; font-size: 16px;}\n"
"        .file-link-even {background-color: #E3F2FD;}\n"
"        .file-link-odd {background-color: #BBDEFB;}\n"
"        .header-bar {background-color: #2C5F7C; color: #FFFFFF; padding: 5px;}\n"
"        .usb-info {background-color: #E3F2FD; border-top: 1px solid #BBDEFB; padding: 5px; text-align: center; margin-top: 20px;}\n"
"        .build-info {font-size: 9px; text-align: left; color: #CCCCCC; padding: 5px 0 0 5px; margin-top: 2px;}\n"
"        .pagination {display: flex; justify-content: center; margin: 15px 0; background-color: #F5F5F5; padding: 8px; border-radius: 3px;}\n"
"        .pagination a, .pagination span {margin: 0 3px; padding: 4px 8px; text-decoration: none; color: #0066CC; border: 1px solid #BBDEFB; background-color: #E3F2FD;}\n"
"        .pagination .current {background-color: #3A7CA5; color: #FFFFFF; border-color: #2C5F7C;}\n"
"        .pagination a:hover {background-color: #BBDEFB;}\n"
"        .page-info {text-align: center; margin: 5px 0; font-size: 14px; color: #666;}\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <div class=\"header\">\n"
"            <img src=\"/logo.jpg\" alt=\"Logo\" align=\"left\" height=\"100%\" style=\"margin-right:10px;\">\n"
"            <h1>USBODE</h1>\n"
"            <h2>USB Optical Drive Emulator</h2>\n"
"        </div>\n"
"\t{{#cdrom}}\n"
"        <div class=\"content\">\n"
"                <h3>File Selection</h3>\n"
"                <div class=\"info-box\">\n"
"                    <p>Current File Loaded: <strong>{{current_image}}</strong></p>\n"
"                </div>\n"
"                <h4>Available Files</h4>\n"
"                {{#links}}\n"
"                <div class=\"file-link file-link-even\"{{{style}}}><a href=\"/mount?file={{file_name}}\">{{display_name}}{{current}}</a></div>\n"
"                {{/links}}\n"
"        \n"
"\t\t{{#pagination}}\n"
"\t\t<div class=\"pagination\">\n"
"\t\t    {{#has_first}}\n"
"\t\t    <a href=\"/?page=1\">1</a>\n"
"\t\t    {{/has_first}}\n"
"\t\t    \n"
"\t\t    {{#has_prev}}\n"
"\t\t    <a href=\"/?page={{prev_page}}\">{{prev_page}}</a>\n"
"\t\t    {{/has_prev}}\n"
"\t\t    \n"
"\t\t    <span class=\"current\">{{current_page}}</span>\n"
"\t\t    \n"
"\t\t    {{#has_next}}\n"
"\t\t    <a href=\"/?page={{next_page}}\">{{next_page}}</a>\n"
"\t\t    {{/has_next}}\n"
"\t\t    \n"
"\t\t    {{#has_last}}\n"
"\t\t    <a href=\"/?page={{last_page}}\">{{last_page}}</a>\n"
"\t\t    {{/has_last}}\n"
"\t\t</div>\n"
"\t\t{{/pagination}}\n"
"        </div>\n"
"\t{{/cdrom}}\n"
"\t{{^cdrom}}\n"
"\t\t<p>Device is in USB Mass Storage Mode</p>\n"
"\t{{/cdrom}}\n"
"        <div class=\"usb-info\">\n"
"                <p>USB Mode: {{ usb_mode }}</p>\n"
"                <div style=\"margin-top: 10px; text-align: center;\">\n"
"                    <a href=\"/config\" class=\"button\">⚙️ Configuration</a>\n"
"                </div>\n"
"        </div>\n"
"        <div class=\"footer\">\n"
"                <p>Version {{ version }}</p>\n"
"            <div class=\"build-info\">\n"
"                    Build: {{ build_info}}\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"</body>\n"
"</html>\n"
""