"\t{{#cdrom}}\n"
"        <div class=\"content\">\n"
"                <h3>File Selection</h3>\n"
"                <div class=\"info-box\">\n"
"                    <p>Current File Loaded: <strong>{{image_name}}</strong></p>\n"
"                </div>\n"
"                <h4>Available Files</h4>\n"
"                {{#links}}\n"
"                <div class=\"file-link file-link-even{{{style}}}\"><a href=\"/mount?file={{file_name}}\">{{display_name}}{{current}}</a></div>\n"
"                {{/links}}\n"
"        \n"
"\t\t{{#pagination}}\n"
"\t\t<div class=\"pagination\">\n"
"\t\t    {{#has_first}}\n"
"\t\t    <a href=\"/?page=1\">1</a>\n"
"\t\t    {{/has_first}}\n"
"\t\t    \n"
"\t\t    {{#has_prev}}\n"
"\t\t    <a href=\"/?page={{prev_page}}\">{{prev_page}}</a>\n"
"\t\t    {{/has_prev}}\n"
"\t\t    \n"
"\t\t    <span class=\"current\">{{current_page}}</span>\n"
"\t\t    \n"
"\t\t    {{#has_next}}\n"
"\t\t    <a href=\"/?page={{next_page}}\">{{next_page}}</a>\n"
"\t\t    {{/has_next}}\n"
"\t\t    \n"
"\t\t    {{#has_last}}\n"
"\t\t    <a href=\"/?page={{last_page}}\">{{last_page}}</a>\n"
"\t\t    {{/has_last}}\n"
"\t\t</div>\n"
"\t\t{{/pagination}}\n"
"        </div>\n"
"\t{{/cdrom}}\n"
"\t{{^cdrom}}\n"
"\t\t<p>Device is in USB Mass Storage Mode</p>\n"
"\t{{/cdrom}}\n"
""