"<h3>Log File</h3>\n"
"<p>This shows the last the 10k of the log file. The entire file is available via FTP or by reading the SD card</p>\n"
"<div id=\"log\">\n"
"{{log_lines}}\n"
"</div>\n"
"\n"
"<div>\n"
"\t<a class=\"button\" href=\"/\">Return to File List</a>\n"
"</div>\n"
""