"<h3>Log File</h3>\n"
"<p>This shows the last the 10k of the log file. The entire file is available via FTP or by reading the SD card</p>\n"
"<div id=\"log\" style=\"width:80%;height:600px;border:1px solid #ccc;padding:8px;\n"
"     overflow-y:scroll;overflow-x:auto;font-family:monospace;\n"
"     white-space:pre;background-color:#f9f9f9;\">\n"
"{{log_lines}}\n"
"</div>\n"
"\n"
"{{#sound_test_available}}\n"
"<form method=\"post\" style=\"margin: 10px 0;\">\n"
"    <input type=\"hidden\" name=\"action\" value=\"soundtest\">\n"
"    <button type=\"submit\" class=\"button\">Execute Sound Test</button>\n"
"</form>\n"
"{{/sound_test_available}}\n"
"\n"
"{{^sound_test_available}}\n"
"<p style=\"color: #666; font-style: italic;\">Sound test not available (not in CDROM mode or sound not enabled)</p>\n"
"{{/sound_test_available}}\n"
"\n"
"{{#message}}\n"
"<div style=\"background-color: #E3F2FD; padding: 10px; margin: 10px 0; border-left: 4px solid #2196F3;\">{{message}}</div>\n"
"{{/message}}\n"
"\n"
"<div>\n"
"\t<a class=\"button\" href=\"/\">Return to File List</a>\n"
"</div>\n"
""