"<h3>Log File</h3>\n"
"<p>This shows the last the 10k of the log file. The entire file is available via FTP or by reading the SD card</p>\n"
"<div id=\"log\" style=\"width:80%;height:600px;border:1px solid #ccc;padding:8px;\n"
"     overflow-y:scroll;overflow-x:auto;font-family:monospace;\n"
"     white-space:pre;background-color:#f9f9f9;\">\n"
"{{log_lines}}\n"
"</div>\n"
"\n"
"<div>\n"
"\t<a class=\"button\" href=\"/\">Return to File List</a>\n"
"</div>\n"
""