"\t<h3>Mounting File</h3>\n"
"\t<div class=\"info-box\">\n"
"\t\t<p>Mode changed - rebooting...</p>\n"
"\t</div>\n"
"\n"
"\t<div>\n"
"\t    <a class=\"button\" href=\"/\">Return to File List</a>\n"
"\t</div>\n"
""