"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <title>USBODE - USB Optical Drive Emulator</title>\n"
"    <style>\n"
"        body {background-color: #EAEAEA; color: #333333; font-family: \"Times New Roman\", serif; margin: 0; padding: 0;}\n"
"        h1, h2, h3 {color: #1E4D8C;}\n"
"        a {color: #0066CC;}\n"
"        a:visited {color: #0066CC;}\n"
"        .container {width: 100%; margin: 0; padding: 0;}\n"
"        .header {background-color: #3A7CA5; padding: 10px; text-align: center; color: #FFFFFF;}\n"
"        .header h1, .header h2 {color: #FFFFFF; margin: 5px 0;}\n"
"        .content {padding: 10px; background-color: #FFFFFF; min-height: 300px;}\n"
"        .footer {background-color: #3A7CA5; padding: 10px; text-align: center; color: #FFFFFF;}\n"
"        .button {background-color: #4CAF50; padding: 7px 15px; text-decoration: none; color: #FFFFFF; margin: 5px; display: inline-block;}\n"
"        .info-box {background-color: #F5F5F5; padding: 10px; margin: 10px 0;}\n"
"        .warning {background-color: #FFDDDD; padding: 10px; margin: 10px 0; color: #990000;}\n"
"        .file-link {padding: 8px; margin: 5px 0; display: block; font-size: 16px;}\n"
"        .file-link-even {background-color: #E3F2FD;}\n"
"        .file-link-odd {background-color: #BBDEFB;}\n"
"        .header-bar {background-color: #2C5F7C; color: #FFFFFF; padding: 5px;}\n"
"        .usb-info {background-color: #E3F2FD; border-top: 1px solid #BBDEFB; padding: 5px; text-align: center; margin-top: 20px;}\n"
"        .build-info {font-size: 9px; text-align: left; color: #CCCCCC; padding: 5px 0 0 5px; margin-top: 2px;}\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <div class=\"header\">\n"
"            <img src=\"/logo.jpg\" alt=\"Logo\" align=\"left\" height=\"100%\" style=\"margin-right:10px;\">\n"
"            <h1>USBODE</h1>\n"
"            <h2>USB Optical Drive Emulator</h2>\n"
"        </div>\n"
"        <div class=\"content\">\n"
"\t<h3>Mounting File</h3>\n"
"\t<div class=\"info-box\">\n"
"\t\t<p>Successfully mounted: <strong>{{image_name}}</strong></p>\n"
"\t</div>\n"
"\n"
"\t<div>\n"
"\t    <a class=\"button\" href=\"/\">Return to File List</a>\n"
"\t</div>\n"
"        </div>\n"
"        <div class=\"usb-info\">\n"
"\t\t<p>USB Mode: {{ usb_mode }}</p>\n"
"        </div>\n"
"        <div class=\"footer\">\n"
"\t\t<p>Version {{ version }}</p>\n"
"            <div class=\"build-info\">\n"
"\t\t    Build: {{ build_info}}\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"</body>\n"
"</html>\n"
""