"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>USBODE - USB Optical Drive Emulator</title>\n"
"        {{#meta_refresh_url}}\n"
"        <meta http-equiv=\"refresh\" content=\"{{meta_refresh_timeout}};url={{meta_refresh_url}}\"/>\n"
"        {{/meta_refresh_url}}\n"
"        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n"
"        <link href=\"/style.css\" rel=\"stylesheet\"/>\n"
"    </head>\n"
"    <body>\n"
"        <div class=\"container\">\n"
"            <div class=\"header\">\n"
"                <a href=\"/\"><img src=\"/logo.jpg\" alt=\"Logo\"></a>\n"
"                <h1>USBODE</h1>\n"
"                <h2>USB Optical Drive Emulator</h2>\n"
"            </div>\n"
"        {{#cdrom}}\n"
"            <div class=\"content\">\n"
"            {{>content}}\n"
"            </div>\n"
"        {{/cdrom}}\n"
"        {{^cdrom}}\n"
"            <p>Device is in USB Mass Storage Mode</p>\n"
"        {{/cdrom}}\n"
"            <div class=\"usb-info\">\n"
"                <p>USB Mode: {{ usb_mode }}</p>\n"
"                <div class=\"center\">\n"
"                    <a href=\"/shutdown\" class=\"button\">Shutdown</a>\n"
"                    <a href=\"/reboot\" class=\"button\">Reboot</a>\n"
"                    <a href=\"/config\" class=\"button\">Configuration</a>\n"
"                    <a href=\"/log\" class=\"button\">Log Viewer</a>\n"
"                </div>\n"
"            </div>\n"
"            <div class=\"footer\">\n"
"                <p>Version {{ version }}</p>\n"
"                <div class=\"build-info\">\n"
"                    Build: {{ build_info}}\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"    </body>\n"
"</html>\n"
""