"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"        <meta charset=\"iso-8859-1\" />\n"
"        <link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" />\n"
"        <title>CDROM Emulator</title>\n"
"</head>\n"
"<body>\n"
"        <h1>Available API Endpoints</h1>\n"
"\t<ul>\n"
"\t\t<li>GET <a href=\"/controller?list\">/controller?list</a> - List available images</li>\n"
"\t\t<li>POST <a href=\"/controller?mount\">/controller?mount=<imagename></a> - Mount the image</li>\n"
"\t</ul>\n"
"\n"
"        <hr />\n"
"        <p class=\"small\">Based on the <a href=\"https://github.com/rsta2/circle\" target=\"_blank\">Circle</a> C++ bare metal environment.</p>\n"
"</body>\n"
"</html>\n"
""